# Generated by Django 4.1.4 on 2023-07-31 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='message',
        ),
    ]
