# Generated by Django 4.1.4 on 2023-07-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0005_alter_description_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
