# Generated by Django 4.1.4 on 2023-07-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0006_alter_description_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
