# Generated by Django 4.1.4 on 2023-08-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0007_description_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('resume_pdf', models.FileField(blank=True, null=True, upload_to='resumes/')),
            ],
        ),
    ]
