# Generated by Django 4.1.4 on 2023-08-10 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0008_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='resume_pdf',
            new_name='resume_file',
        ),
    ]
