# Generated by Django 4.1.4 on 2023-08-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0010_front_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='front_images',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
