# Generated by Django 4.1.4 on 2023-08-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0011_front_images_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='front_images',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='front_images',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
