# Generated by Django 4.1.4 on 2023-08-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0012_front_images_name_alter_front_images_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=10, null=True)),
                ('natinality', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
