# Generated by Django 4.1.4 on 2023-08-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0013_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
